### ISSUE TITLE
Request a paper for this entire project

### ISSUE THREAD

**Issue by q576333** [noeperez/indires_navigation#1]
Hi Guys
First of all, Thanks for your good job.
I am a graduate student from Taiwan.
Today, I found this project from Internet that are so close my research topic.
So I want ask you, Do you have this whole project paper can be a reference?
I looking forward to your reply. Thank you!

**Comment by noeperez** [comment]
Hello,

Thank you very much for your interest.
We have a journal paper that is under reviewing at the moment. Hopefully,
it will be published in a month. No more than two.
Meanwhile, I can just try to answer the possible questions that you can
have.
Sorry for the inconvenience.

Best regards,
Noé

**Comment by noeperez** [comment]
You can find the paper here: https://doi.org/10.3390/s20010220
